### ISSUE TITLE
Update composer package name?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Sitemap#20]
Excluding the `loadsys_codesniffer` (which must avoid dashes in the filesystem path), our Packagist packages follow a naming convention of using dashes in the package name: https://packagist.org/packages/loadsys/

It would only be a superficial improvement to convert the name to match and might cause problems for any consuming projects (are there any that we should be concerned with) to change the package name.

Only if the impact is low would this be worth doing after the fact (now).

**Comment by jtyost2** [comment]
In short we probably can't easily:

> Please make sure you have read the package naming conventions before submitting your package. The authoritative name of your package will be taken from the composer.json file inside the master branch or trunk of your repository, and it can not be changed after that. [Cite](https://packagist.org/packages/submit)

> First of all, you must pick a package name. This is a very important step since it can not change and it should be unique enough to avoid conflicts in the future. [Cite](https://packagist.org/about)

Probably the only way to do so is to abandon the current package from Packagist and then possibly create a new package, but I'm not sure that would work.

I've updated the Plugin Skeleton to reflect this information.
