### ISSUE TITLE
How to call the sitemap.xml

### ISSUE THREAD

**Issue by Isengo1989** [loadsys/CakePHP-Sitemap#37]
I used the Docs to install and configure it. My very simple Question is how to view it, the Plugin/config/routes.php let me guess it is Domain/sitemap oder /sitemap.xml , but this just shows:

```
Documentation API
Error: SitemapController could not be found.

Error: Create the class SitemapController below in file: src/Controller/SitemapController.php
```

**Comment by justinyost** [comment]
Which version are you attempting to use? The Cake2 or Cake3 version.

**Comment by justinyost** [comment]
Closing as no feedback in a while.
