### ISSUE TITLE
Test do not pass your own cs standard

### ISSUE THREAD

**Issue by elboletaire** [loadsys/CakePHP-Sitemap#38]
I've just forked your plugin in order to fix #37 and when I run de code sniffer, it crashes with three errors and 4 warnings.

![imatge](https://cloud.githubusercontent.com/assets/153305/20138874/4e92c89e-a683-11e6-8c17-3d01b3a7774b.png)

**Comment by justinyost** [comment]
Closing post merge of PR #46
