### ISSUE TITLE
Add handpicked results

### ISSUE THREAD

**Issue by elboletaire** [loadsys/CakePHP-Sitemap#42]
It would be very nice to have an option to add hand-picked links. In my case, the home page does not directly depend from an entity and I would like to add it to the generated `sitemap.xml` file.

I guess that using an array in the `Sitemap` configuration like this one: 

```
'handpicked' => [
  [
    'route' => ['_name' => 'my_route'],
    'changefreq' => 'weekly',
    'priority' => 0.7
  ]
]
```

**Comment by justinyost** [comment]
Not particularly interested in building this out. This is of nominal value for us.

The more important thing we (for us) want to build out is the ability to loop over the Pages static files and list those. https://github.com/loadsys/CakePHP-Sitemap/issues/31

**Comment by justinyost** [comment]
Would the above solve your problem or are you still envisioning needing a static link ability?

**Comment by elboletaire** [comment]
We do need it, so I'll make it on our fork.

**Comment by elboletaire** [comment]
Sorry I understood it wrong. Of course the above solution would be ok for me :)
