### ISSUE TITLE
Missing Docu

### ISSUE THREAD

**Issue by Isengo1989** [loadsys/CakePHP-Sitemap#47]
I installed the plugin via composer - added the behavior etc.

I am missing the docu how to view any of this. Could you add this to the readme?

**Comment by ricog** [comment]
Hi @Isengo1989. Thanks for pointing that out. We are considering adding a default route too. For now you can add this at the bottom of your `config/routes.php` and then you will be able to access the sitemap at `/sitemap.xml`.

```php
Router::scope('/sitemap', function (RouteBuilder $routes) {
    $routes->extensions(['xml']);
    $routes->connect('/', [
        'plugin' => 'Sitemap',
        'controller' => 'Sitemaps',
        'action' => 'index'
    ]);
});```

**Comment by ricog** [comment]
A default route of `/sitemap.xml` has been added, and the docs are now updated.

**Comment by Isengo1989** [comment]
Thanks @ricog !
