### ISSUE TITLE
Problem with XML file when PHP short tag is enabled

### ISSUE THREAD

**Issue by royalfoxie** [loadsys/CakePHP-Sitemap#49]
Hi!

I found problem in index.ctp (/loadsys/cakephp_sitemap/src/Template/Sitemaps/xml/index.ctp). 

The XML file report 500 error in first line because on my host PHP short tags is enabled. 

I have simple solution because I can't off short tags on my host. Put it below.

BEFORE
`<?xml version="1.0" encoding="UTF-8"?>`

AFTER
`<?= '<?xml version="1.0" encoding="UTF-8"?>'; ?>`

**Comment by ricog** [comment]
Thank you for the proposal. Do you mind submitting a pull request and I'll include it? Also, you should be able to leave the semi-colon off.
